### PR TITLE
Remove the entire flag/mode/call type system and flags column

### LINKED ISSUE #44: Remove flags
Flags should safely be able to be removed now. All of their functionality which I can find has been achieved through other means.

### PR DESCRIPTION
**Pull request by elifoster**
@Alexia code review? <3 <3 <3

Closes #44

### CODE REVIEW

**Comment by elifoster** [comment]
(Authors cannot review their own PRs)

It looks like I, as usual, forgot to add the schema update thing in `OreDict.hooks.php`. I'll need to do that before this can be merged.

@Alexia Could you perhaps review this?

**Comment by Alexia** [comment]
This looks good to me!

**Comment by elifoster** [comment]
@Alexia You seem to know more about the schema update thing than I, and the docs weren't very helpful. Just to verify, this is correct for this, right?
```php
$updater->addExtensionUpdate(['modifyField', 'ext_oredict_items', "{$extDir}/upgrade/sql/remove_flags.sql", true]);
```

**Comment by Alexia** [comment]
Yeah, the documentation for the updater system is lacking.

Usually if I need to drop one or more fields and/or also make changes to indexes I use modifyField.  However, if only just dropping a single field there is an option for that.  Both modifyField and dropField require the field name as the third array parameter.

```
$updater->addExtensionUpdate(['dropField', 'ext_oredict_items', 'flags', "{$extDir}/upgrade/sql/ext_oredict_items/drop_flags.sql", true]);
```

**Pull request merged**
